name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:
      - name: Build
        uses: whyakari/kernel_build_action@v1
        with:
          kernel-url: whyakari/android_kernel_xiaomi_ginkgo
          kernel-dir: ginkgo
          branch: fourteen
          config: moe_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          python-2.7: true
          ksu: true
          ksu-version: main
          android-version: 13
          aosp-clang-version: r383902
          python-27: true
          disable-lto: false
          overlayfs: true
          lxc: false
          lxc-patch: false
          anykernel3: true
